service: erp-demo

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: ${opt:stage, 'dev'}
  environment:
    DATABASE_URI: ${env:DATABASE_URI}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    JWT_PASSPHRASE: ${env:JWT_PASSPHRASE}
    JWT_TOKEN_EXPIRATION: ${env:JWT_TOKEN_EXPIRATION}
    BCRYPT_SALT_ROUNDS: ${env:BCRYPT_SALT_ROUNDS}
    NODE_ENV: production
    CORS_ORIGIN: ${env:CORS_ORIGIN, '*'}

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi: '*'
    timeout: 30

package:
  exclude:
    - .env
    - .git/**
    - node_modules/.cache/**
    - resume.html
